const ActionTypes = {
  ADD_NEW_ITEM: 'ADD_NEW_ITEM',
  ITEM_SELECTED: 'ITEM_SELECTED',
  ADD_STATIC_TEXT: 'ADD_STATIC_TEXT',
  ADD_NUMBER_FIELD: 'ADD_NUMBER_FIELD',
  ADD_TEXT_RESULT_FIELD: 'ADD_TEXT_RESULT_FIELD',
  CHANGE_ITEM_HEADER: 'CHANGE_ITEM_HEADER',
  CHANGE_ITEM_TEXT: 'CHANGE_ITEM_TEXT',
  LAYOUT_CHANGED: 'LAYOUT_CHANGED',
}

export default ActionTypes
