const ActionTypes = {
  ADD_NEW_ITEM: 'ADD_NEW_ITEM',
  ITEM_SELECTED: 'ITEM_SELECTED',
  ADD_STATIC_TEXT: 'ADD_STATIC_TEXT',
  ADD_NUMBER_FIELD: 'ADD_NUMBER_FIELD',
  ADD_TEXT_RESULT_FIELD: 'ADD_TEXT_RESULT_FIELD',
}

export default ActionTypes
