const ActionTypes = {
  ADD_NEW_ITEM: 'ADD_NEW_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_STATIC_TEXT: 'ADD_STATIC_TEXT',
  ADD_NUMBER_FIELD: 'ADD_NUMBER_FIELD',
  ADD_NUMBER_RESULT_FIELD: 'ADD_NUMBER_RESULT_FIELD',
  ADD_DROPDOWN_FIELD: 'ADD_DROPDOWN_FIELD',
  CHANGE_ITEM_HEADER: 'CHANGE_ITEM_HEADER',
  CHANGE_ITEM_TEXT: 'CHANGE_ITEM_TEXT',
  CHANGE_INPUT_ORDER: 'CHANGE_INPUT_ORDER',
  CHANGE_HIDDEN_LABEL: 'CHANGE_HIDDEN_LABEL',
  CHANGE_FORMULA: 'CHANGE_FORMULA',
  CHANGE_ITEM_SETTINGS: 'CHANGE_ITEM_SETTINGS',

  ITEM_SELECTED: 'ITEM_SELECTED',
  LAYOUT_CHANGED: 'LAYOUT_CHANGED',
  CALCULATABLE_VALUE_CHANGED: 'CALCULATABLE_VALUE_CHANGED',
}

export default ActionTypes
